steps:
  - id: yarnClient
    name: node
    entrypoint: yarn
    dir: './client'
  - id: buildClient
    name: node
    entrypoint: yarn
    args: ['build']
    waitFor:
      - yarnClient
  - id: yarnServer
    entrypoint: yarn
    dir: './server'
    name: node
    waitFor: ['-']
  - id: deploytoAppEngine
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', './app.yaml', '--stop-previous-version']
    timeout: '1200s'
    waitFor:
      - yarnServer
      - buildClient
